trigger:
  branches:
    include:
      - main
  paths:
    include:
      - '**'

pool:
  vmImage: ubuntu-latest

variables:
  azureSubscription: 'Ari-Terraform-Auth'
  workingDirectory: 'environments/dev'
  acrLoginServer: 'acrcapstoneari999.azurecr.io'
  backendRG: 'ari-terraform-storage-rg'
  backendStorageAccount: 'aristate12345'
  backendContainer: 'tfstate'
  backendKey: 'dev.terraform.tfstate'

stages:
# Stage 1: Initialize and Validate
- stage: Initialize
  displayName: 'Initialize & Validate Terraform'
  jobs:
  - job: TerraformInit
    displayName: 'Terraform Init & Validate'
    steps:
    - checkout: self

    - script: |
        sudo apt-get update
        sudo apt-get install -y gnupg software-properties-common curl
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
        sudo apt-get update
        sudo apt-get install -y terraform
      displayName: Install Terraform

    - script: terraform version
      displayName: Verify Terraform

    - task: AzureCLI@2
      displayName: 'Terraform Init, Plan, & Apply'
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        workingDirectory: $(workingDirectory)
        addSpnToEnvironment: true 
        inlineScript: |
          set -e
          echo "Setting up Authentication..."
          export ARM_CLIENT_ID=$servicePrincipalId
          export ARM_CLIENT_SECRET=$servicePrincipalKey
          export ARM_TENANT_ID=$tenantId
          export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)

          echo "Cleaning up local state files..."
          rm -f terraform.tfstate*
          rm -rf .terraform
          rm -f .terraform.lock.hcl

          echo "Running Terraform Init..."
          terraform init -reconfigure -upgrade \
            -backend-config="resource_group_name=$(backendRG)" \
            -backend-config="storage_account_name=$(backendStorageAccount)" \
            -backend-config="container_name=$(backendContainer)" \
            -backend-config="key=$(backendKey)"

          echo "Importing existing Azure resources (if any)..."
          set +e  # Don't exit on error for imports

          terraform import -var="docker_image_name=frontend:latest" \
            module.dev_infra.azurerm_resource_group.rg \
            /subscriptions/606e824b-aaf7-4b4e-9057-b459f6a4436d/resourceGroups/ari-rg-capstone-dev

          terraform import -var="docker_image_name=frontend:latest" \
            module.dev_infra.azurerm_container_registry.acr \
            /subscriptions/606e824b-aaf7-4b4e-9057-b459f6a4436d/resourceGroups/ari-rg-capstone-dev/providers/Microsoft.ContainerRegistry/registries/acrcapstoneari999

          terraform import -var="docker_image_name=frontend:latest" \
            module.dev_infra.azurerm_kubernetes_cluster.aks \
            /subscriptions/606e824b-aaf7-4b4e-9057-b459f6a4436d/resourceGroups/ari-rg-capstone-dev/providers/Microsoft.ContainerService/managedClusters/aks-capstone-dev

          terraform import -var="docker_image_name=frontend:latest" \
            module.dev_infra.azurerm_service_plan.plan \
            /subscriptions/606e824b-aaf7-4b4e-9057-b459f6a4436d/resourceGroups/ari-rg-capstone-dev/providers/Microsoft.Web/serverFarms/plan-capstone-dev

          terraform import -var="docker_image_name=frontend:latest" \
            module.dev_infra.azurerm_linux_web_app.webapp \
            /subscriptions/606e824b-aaf7-4b4e-9057-b459f6a4436d/resourceGroups/ari-rg-capstone-dev/providers/Microsoft.Web/sites/app-capstone-ui-dev-ari999

          terraform import -var="docker_image_name=frontend:latest" \
            module.dev_infra.azurerm_postgresql_flexible_server.postgres \
            /subscriptions/606e824b-aaf7-4b4e-9057-b459f6a4436d/resourceGroups/ari-rg-capstone-dev/providers/Microsoft.DBforPostgreSQL/flexibleServers/psql-capstone-dev-ari999

          terraform import -var="docker_image_name=frontend:latest" \
            module.dev_infra.azurerm_postgresql_flexible_server_database.capstone_db \
            /subscriptions/606e824b-aaf7-4b4e-9057-b459f6a4436d/resourceGroups/ari-rg-capstone-dev/providers/Microsoft.DBforPostgreSQL/flexibleServers/psql-capstone-dev-ari999/databases/capstone_db

          terraform import -var="docker_image_name=frontend:latest" \
            module.dev_infra.azurerm_postgresql_flexible_server_firewall_rule.allow_azure \
            /subscriptions/606e824b-aaf7-4b4e-9057-b459f6a4436d/resourceGroups/ari-rg-capstone-dev/providers/Microsoft.DBforPostgreSQL/flexibleServers/psql-capstone-dev-ari999/firewallRules/allow-azure-access

          terraform import -var="docker_image_name=frontend:latest" \
            module.dev_infra.azurerm_api_management.apim \
            /subscriptions/606e824b-aaf7-4b4e-9057-b459f6a4436d/resourceGroups/ari-rg-capstone-dev/providers/Microsoft.ApiManagement/service/apim-capstone-dev-ari999

          echo "Azure resource import phase complete (errors ignored if resources already in state)"
          set -e  # Re-enable exit on error

          echo "Fixing corrupted Kubernetes resources..."
          set +e  # Don't exit on error

          # Get AKS credentials
          az aks get-credentials --resource-group $(aksResourceGroup) --name $(aksClusterName) --overwrite-existing

          # Delete existing deployments and services from Kubernetes
          kubectl delete deployment owasp-zap -n security --ignore-not-found=true
          kubectl delete deployment trivy-server -n security --ignore-not-found=true
          kubectl delete service owasp-zap -n security --ignore-not-found=true
          kubectl delete service trivy-server -n security --ignore-not-found=true

          # Remove from Terraform state
          terraform state rm module.k8s_addons.kubernetes_service.owasp_zap 2>/dev/null || echo "owasp_zap service not in state"
          terraform state rm module.k8s_addons.kubernetes_service.trivy_server 2>/dev/null || echo "trivy_server service not in state"
          terraform state rm module.k8s_addons.kubernetes_deployment.owasp_zap 2>/dev/null || echo "owasp_zap deployment not in state"
          terraform state rm module.k8s_addons.kubernetes_deployment.trivy_server 2>/dev/null || echo "trivy_server deployment not in state"

          set -e

          echo "Breaking any existing state locks before plan..."
          az storage blob lease break \
            --account-name $(backendStorageAccount) \
            --container-name $(backendContainer) \
            --blob-name $(backendKey) \
            --lease-break-period 0 \
            --auth-mode key 2>/dev/null || echo "No lock to break"

          echo "Running Terraform Plan..."
          terraform plan \
            -var="docker_image_name=frontend:latest" \
            -out=tfplan

          echo "Running Terraform Apply..."
          terraform apply -auto-approve tfplan