apiVersion: v1
kind: Service
metadata:
  name: backend-a-service
  namespace: microservices-app
  labels:
    app: backend-a
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: backend-a
---
apiVersion: v1
kind: Service
metadata:
  name: backend-b-service
  namespace: microservices-app
  labels:
    app: backend-b
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: backend-b
