apiVersion: v1
kind: Service
metadata:
  name: loki-external
  namespace: monitoring
spec:
  type: LoadBalancer
  ports:
    - port: 3100
      targetPort: 3100
      protocol: TCP
      name: http
  selector:
    app: loki
